name: Copy Files to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to DigitalOcean server
        run: |
          scp -r ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_AGENT_DEBUG: 1
