name: Deploy Node.js Application to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to DigitalOcean server
        run: rsync -avz --delete ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/sample

      - name: Install dependencies
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd sample && npm install"

      - name: Restart application
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "pm2 restart all"  # Assuming PM2 is used to manage your Node app
